version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sourcemaps"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-o8j33398vw3b"
s3_prefix = "sourcemaps"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
